### ISSUE TITLE
Weight for Height/Length should use different parameters as per age

### ISSUE THREAD

**Issue by Parth7223** [OpenCHS/rules-config#36] opened 2024-04-03 03:43 UTC
Currently we have weight for height logic to consider severe acute malnutrition and moderate acute malnutrition status for any child which does not have different parameters as per the age. (We are using parameters of 0-2 years old child for height 45cm to 104.5cm and parameters of 2-5 years old child for height 105 to 120).

As per WHO guidelines, parameters for child of 0-2 years should be different from 2-5 years. Please refer to the WHO parameters provided here. 

 [WHL-Boys 0-2 years](https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/weight-for-length-height/wfl-boys-0-2-zscores.pdf?sfvrsn=f8e6ec4f_9)
[WHL-Boys 2-5 years](https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/weight-for-length-height/wfh-boys-2-5-zscores.pdf?sfvrsn=66c3e6fe_9)
[WHL-Girls 0-2 years](https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/weight-for-length-height/wfl-girls-0-2-zscores.pdf?sfvrsn=9d1afef2_9)
[WHL-Girls 2-5 years](https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/weight-for-length-height/wfh-girls-2-5-zscores.pdf?sfvrsn=3dc8f085_9)

**Comment by vinayvenu** [comment] 2024-04-03 04:28
@Parth7223 please don't assign anyone to the card. It can cause confusion. 

@mahalakshme when we fix this, any change we do should not break the growth chart.

**Comment by mahalakshme** [comment] 2024-05-10 12:16
@Parth7223 duplicate of https://github.com/avniproject/avni-client/issues/1232, so closing this.

**Closed as completed by mahalakshme** 2024-05-10 12:16 UTC
Labels: user reported
